[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.18"
fuzz_runs = 5000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
mainnet = "${ALCHEMY_url}"
# rinkeby = "${RINKEBY_RPC}"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${GOERLI_ETHERSCAN_API_KEY}" }
